Проект ShareIt. Техническое задание. Часть 1
ZherebtsovAA/java-shareit pull request #1
Opened 2023-06-18 08:31 UTC by ZherebtsovAA

2023-06-18 18:47 UTC, ohelly requested changes
Привет! Отлично выполненная работа, все работает корректно. Оставил ряд рекомендаций - их выполнение на твое усмотрение. Обрати внимание, что ряд рекомендаций(например с опционалами) в подмодуле user также применим и к подмодулю item,

2023-06-18 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  package ru.practicum.shareit.item;
Рекомендация: Контроллер можно вынести в отдельный пакет - controller, аналогично можно сделать и с сервисами, мапперами и репозиториями.
Рекомендация также применима и к остальным подмодулям.

2023-06-18 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public final class ItemMapper {
Рекомендация: Для маппером также можно использовать mapstruct, очень полезная вещь и довльно часто встречается.
https://www.baeldung.com/mapstruct

2023-06-18 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Рекомендация: Над методами, которые что-то достают из БД или сохраняют, рекомендуется использовать аннотацию ``@Transactional``. Транзакции в целом очень важная тема и о них нужно знать. На собеседованиях будут спрашивать 100%

2023-06-18 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (result.isEmpty()) {
Рекомендация: У опционала есть удобный метод - orElseThrow
![image](https://github.com/ZherebtsovAA/java-shareit/assets/51891976/d40cd03d-fbfd-4569-9fde-ed87e3af7048)

2023-06-18 18:47 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemoryImpl.java
> +        if (users.containsKey(userId)) {
Рекомендация: В данном методе можно использовать Optional.ofNullable
![image](https://github.com/ZherebtsovAA/java-shareit/assets/51891976/77133e6f-48b9-46c1-add2-6c00e3a77db5)

2023-06-19 04:52 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  package ru.practicum.shareit.item;
Контроллеры, сервисы, мапперы, репозитории вынесены в соответствующие пакеты для всех модулей.

2023-06-19 05:28 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (result.isEmpty()) {
Исправлено во всех модулях.

2023-06-19 06:59 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemoryImpl.java
> +        if (users.containsKey(userId)) {
Исправлено в подмодуле: user, item.

2023-06-20 09:21 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public final class ItemMapper {
Переписано с использованием mapstruct. Фух, оно еще и работает.

2023-06-22 01:30 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
В сервисы добавлено использование аннотации @Transactional

2023-06-22 18:27 UTC, ohelly approved these changes
Привет! Все супер, отлично выполненная работа. Можно двигаться дальше. Удачи!

2023-06-23 02:32 UTC, merged