Выполнена доработка проекта ShareIt согласно технического задания №14
ZherebtsovAA/java-shareit pull request #2
Opened 2023-07-03 06:18 UTC by ZherebtsovAA

2023-07-03 22:07 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает корректно. Есть пара моментов, которые стоит поправить + одна рекомендация.

2023-07-03 22:07 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Необходимо испарвить: Не рекомендуется ставить аннотацию ``@Data`` над сущностями. Здесь хорошее объяснение
https://habr.com/ru/companies/haulmont/articles/564682/

Относится также и к другим сущностям

2023-07-03 22:07 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Optional<User> findByEmailContainingIgnoreCase(String emailSearch);
Необходимо исправить: Необходимо искать точно по емейлу, а не по вхождению. email@test.com не равен 12email@test.com
Можно заменить просто на ``findByEmail``

2023-07-03 22:07 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findByAvailable(available).stream()
Рекомендация: В данном случае лучше сразу запросом доставать подхоядщие под запрос элементы, иначе итерироваться по всем доступным предметам будет очень ресурснозатратно.
Условно, в БД 10000 доступных предметов, а подходящих под запрос только 100. В твоем случае все 10к записей выгрузятся в приложение.

2023-07-04 04:39 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Для всех моделей сущностей @Data заменена на @Getter, @Setter, @ToString, @RequiredArgsConstructor. Переопределены методы equals() и hashCode(). Lazy поля помечены аннотацией @ToString.Exclude.

2023-07-04 07:44 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Optional<User> findByEmailContainingIgnoreCase(String emailSearch);
Исправлено.

2023-07-04 09:26 UTC, ZherebtsovAA commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findByAvailable(available).stream()
Исправлено: реализовано запросом в БД.

2023-07-04 20:36 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-07-05 10:28 UTC, merged